# Generated by Django 3.0.5 on 2020-08-17 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200817_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Image'),
        ),
    ]
