# Generated by Django 3.1.1 on 2020-09-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200817_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='px32',
            new_name='px64',
        ),
    ]
