# Generated by Django 3.1.1 on 2020-12-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_playlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uri',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='uri',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='uri',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
