# Generated by Django 3.1.1 on 2020-12-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20201228_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default=None, max_length=64, unique=True),
        ),
    ]
