# Generated by Django 3.1.1 on 2020-12-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20201229_1521'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('user', 'played_at'), name='Can not have two streams in the same moment'),
        ),
    ]
