# Generated by Django 3.1.1 on 2021-04-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='coingecko_id',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
