# Generated by Django 3.1.1 on 2021-05-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20210407_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='queue',
            field=models.TextField(default='[]'),
        ),
    ]
