# Generated by Django 3.1.13 on 2021-11-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20210531_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
