# Generated by Django 3.1.13 on 2021-11-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_album_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='passenger',
        ),
    ]
