# Generated by Django 3.1.13 on 2021-11-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_remove_profile_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='queue',
            new_name='search_history',
        ),
    ]
