# Generated by Django 3.1.13 on 2021-12-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20211127_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='extra_data',
            field=models.TextField(default='{}'),
        ),
    ]
