# Generated by Django 3.1.13 on 2022-03-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_playlist_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='danceability',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='energy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='valence',
            field=models.FloatField(default=0),
        ),
    ]
