# Generated by Django 3.0.5 on 2022-07-10 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20220304_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_change_trend', models.CharField(choices=[('up', 'up'), ('down', 'down'), ('new', 'new'), ('constant', 'constant')], default='new', max_length=32)),
                ('ranking_change_amount', models.IntegerField(max_length=8)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Song')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(through='backend.Ranking', to='backend.Song'),
        ),
    ]
