# Generated by Django 3.0.5 on 2022-07-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20220710_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='ranking_change_amount',
            field=models.IntegerField(),
        ),
    ]
