# Generated by Django 3.0.5 on 2022-07-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_auto_20220710_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='ranking_change_amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
