# Generated by Django 3.0.5 on 2022-07-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20220710_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='ranking',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
