# Generated by Django 3.1.13 on 2022-07-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_ranking_ranking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ['ranking']},
        ),
    ]
