# Generated by Django 3.1.13 on 2022-07-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20220711_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='compatibility',
            field=models.FloatField(default=0),
        ),
    ]
