# Generated by Django 3.1.13 on 2022-07-15 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_ranking_compatibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ForeignKey(default=232, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.image'),
            preserve_default=False,
        ),
    ]
