# Generated by Django 3.1.13 on 2022-07-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_playlist_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ['ranking_position']},
        ),
        migrations.RenameField(
            model_name='ranking',
            old_name='ranking',
            new_name='ranking_position',
        ),
    ]
