# Generated by Django 3.1.13 on 2022-07-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_auto_20220717_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='new_entries_amount',
            field=models.IntegerField(default=0),
        ),
    ]
