# Generated by Django 3.0.5 on 2022-07-20 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0037_playlist_new_entries_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='members',
            field=models.ManyToManyField(related_name='playlists_as_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
