# Generated by Django 3.0.5 on 2022-07-20 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0038_playlist_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='members',
            field=models.ManyToManyField(related_name='playlist_as_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
