# Generated by Django 3.0.5 on 2022-07-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_songrecommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songrecommendation',
            old_name='Description',
            new_name='description',
        ),
    ]
