# Generated by Django 3.0.5 on 2022-07-26 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0041_auto_20220726_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrecommendation',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recommendation_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
