# Generated by Django 3.0.5 on 2022-07-27 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_auto_20220726_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ForeignKey(default=266, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Image'),
        ),
    ]
