# Generated by Django 3.0.5 on 2022-07-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_auto_20220727_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
