# Generated by Django 3.0.5 on 2022-08-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_endsongfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='endsongfile',
            name='cleaned',
            field=models.BooleanField(default=False),
        ),
    ]
