# Generated by Django 3.0.5 on 2022-08-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_endsongfile_cleaned'),
    ]

    operations = [
        migrations.AddField(
            model_name='endsongfile',
            name='uris_available_in_database',
            field=models.CharField(choices=[('unverified', 'unverified'), ('available', 'available'), ('processing', 'processing'), ('error', 'error')], default='unverified', max_length=24),
        ),
    ]
