# Generated by Django 3.0.5 on 2022-08-14 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_endsongfile_uris_available_in_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='endsongfile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
