# Generated by Django 3.0.5 on 2022-08-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_endsongfile_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endsongfile',
            old_name='timestamp',
            new_name='upload_timestamp',
        ),
    ]
