# Generated by Django 3.0.5 on 2022-08-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_auto_20220814_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='endsongfile',
            name='import_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
