# Generated by Django 3.0.5 on 2022-08-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_auto_20220814_2307'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stream',
            name='Can not have two streams in the same moment',
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('user', 'played_at', 'imported'), name='Can not have two streams in the same moment (unless one is imported)'),
        ),
    ]
