# Generated by Django 3.0.5 on 2022-08-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_stream_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='stream',
            name='Can not have two streams in the same moment (unless one is imported)',
        ),
        migrations.AddField(
            model_name='album',
            name='album_type',
            field=models.CharField(choices=[('album', 'album'), ('single', 'single'), ('appears_on', 'appears_on'), ('compilation', 'compilation')], default='album', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('song', 'user', 'played_at', 'imported'), name='Can not stream the same song twice in the same moment (unless one is imported)'),
        ),
        migrations.AddField(
            model_name='albumcontainer',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Artist'),
        ),
        migrations.AddField(
            model_name='albumcontainer',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Image'),
        ),
        migrations.AddField(
            model_name='albumcontainer',
            name='master_child_album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Album'),
        ),
    ]
