# Generated by Django 3.0.5 on 2022-08-15 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_auto_20220815_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_container',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.AlbumContainer'),
        ),
    ]
