# Generated by Django 3.0.5 on 2022-08-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_album_album_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_type',
            field=models.CharField(choices=[('album', 'album'), ('single', 'single'), ('appears_on', 'appears_on'), ('compilation', 'compilation'), ('unknown', 'unknown')], default='unknown', max_length=100),
        ),
    ]
