# Generated by Django 3.1 on 2022-08-19 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_auto_20220816_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_container',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.albumcontainer'),
        ),
    ]
