# Generated by Django 3.1.13 on 2022-08-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_songcontainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songcontainer',
            old_name='master_child_album',
            new_name='master_child_song',
        ),
        migrations.RemoveField(
            model_name='albumcontainer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='songcontainer',
            name='image',
        ),
    ]
