# Generated by Django 3.1.13 on 2022-08-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_auto_20220823_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_container',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.songcontainer'),
        ),
    ]
