# Generated by Django 3.1.13 on 2022-08-23 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_auto_20220823_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='songcontainer',
            name='album_container',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.albumcontainer'),
            preserve_default=False,
        ),
    ]
