# Generated by Django 3.1.13 on 2022-08-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_songcontainer_album_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='songcontainer',
            name='bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='songcontainer',
            name='track_number',
            field=models.IntegerField(default=0),
        ),
    ]
