# Generated by Django 3.1.13 on 2022-08-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_auto_20220823_2155'),
    ]

    operations = [

    ]
