# Generated by Django 3.1 on 2022-08-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_auto_20220823_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcontainer',
            name='album_type',
            field=models.CharField(choices=[('album', 'album'), ('single', 'single'), ('appears_on', 'appears_on'), ('compilation', 'compilation'), ('unknown', 'unknown')], default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='songcontainer',
            name='disc_number',
            field=models.IntegerField(default=0),
        ),
    ]
