# Generated by Django 3.2.15 on 2022-09-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_alter_recommendationplaylist_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='songrecommendation',
            constraint=models.UniqueConstraint(fields=('user_from', 'user_to', 'song'), name='Can not recommend a user the same song twice'),
        ),
    ]
