# Generated by Django 3.2.15 on 2022-09-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_albumcontainer_album_type'),
        ('backend', '0071_songrecommendation_can not recommend a user the same song twice'),
    ]

    operations = [
    ]
