# Generated by Django 3.2.15 on 2022-11-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_alter_socialdisplaysession_log_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialdisplaysession',
            name='log_file',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
