# Generated by Django 3.2.15 on 2022-11-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_socialdisplaysession_active_session_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialdisplaysession',
            old_name='active_session_time',
            new_name='active_session_duration',
        ),
    ]
