# Generated by Django 3.2.15 on 2022-11-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0078_rename_active_session_time_socialdisplaysession_active_session_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialdisplaysession',
            name='log_file',
        ),
    ]
