# Generated by Django 3.2.15 on 2022-11-03 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0079_remove_socialdisplaysession_log_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialDisplayUserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility', models.FloatField()),
                ('session_affinity', models.FloatField()),
                ('cumulative_user_session_time', models.FloatField()),
                ('time_delta', models.FloatField()),
                ('valid_update', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.socialdisplaysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
