# Generated by Django 3.2.15 on 2022-11-08 09:11

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0082_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=backend.models.group_directory_path),
        ),
    ]
