# Generated by Django 3.2.15 on 2022-11-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0084_alter_group_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='identifier',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
