# Generated by Django 3.2.15 on 2022-11-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0086_groupmembership'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='Can not join the same group twice'),
        ),
    ]
