# Generated by Django 3.2.15 on 2022-12-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0088_group_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='songcontainer',
            name='uri',
            field=models.CharField(default='?', max_length=64),
        ),
    ]
