# Generated by Django 3.2.15 on 2022-12-21 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0090_genrecontainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('playlist_id', models.TextField()),
                ('sort_mode', models.CharField(choices=[('streams', 'streams'), ('compatibility', 'compatibility')], default='streams', max_length=32)),
                ('update', models.BooleanField()),
                ('new_entries_amount', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.TextField(default='{}')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.group')),
                ('image', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.image')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_position', models.IntegerField()),
                ('ranking_change_trend', models.CharField(choices=[('up', 'up'), ('down', 'down'), ('new', 'new'), ('constant', 'constant')], default='new', max_length=32)),
                ('ranking_change_amount', models.IntegerField(blank=True, default=None, null=True)),
                ('compatibility', models.FloatField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.groupplaylist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.song')),
            ],
            options={
                'ordering': ['ranking_position'],
            },
        ),
        migrations.AddField(
            model_name='groupplaylist',
            name='songs',
            field=models.ManyToManyField(through='backend.GroupRanking', to='backend.Song'),
        ),
        migrations.AddField(
            model_name='groupplaylist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
