# Generated by Django 3.2.15 on 2022-12-30 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0093_alter_usercacheobject_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCacheObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=None, max_length=128, unique=True)),
                ('cache_type', models.CharField(choices=[('songs', 'songs'), ('artists', 'artists'), ('albums', 'albums')], default='undefined', max_length=16)),
                ('sort_mode', models.CharField(choices=[('streams', 'streams'), ('compatibility', 'compatibility')], default='undefined', max_length=16)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.group')),
            ],
        ),
    ]
