# Generated by Django 3.2.15 on 2022-12-30 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0094_groupcacheobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcacheobject',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupcacheobject',
            name='invalidated_subcache_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupcacheobject',
            name='timeframe',
            field=models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly'), ('quarterly', 'quarterly'), ('yearly', 'yearly'), ('all-time', 'all-time'), ('YTD', 'YTD')], default='undefined', max_length=16),
        ),
        migrations.AddField(
            model_name='usercacheobject',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercacheobject',
            name='timeframe',
            field=models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly'), ('quarterly', 'quarterly'), ('yearly', 'yearly'), ('all-time', 'all-time'), ('YTD', 'YTD')], default='undefined', max_length=16),
        ),
    ]
